# Generated by Django 3.1 on 2020-10-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('slogan', models.CharField(max_length=120)),
                ('localizacao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=600)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=600)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituto')),
            ],
        ),
    ]
