# Generated by Django 3.1 on 2020-10-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_instituto_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donoinstituto'),
        ),
    ]
