# Generated by Django 3.1 on 2020-10-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201030_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donoinstituto',
            name='id',
        ),
        migrations.AlterField(
            model_name='donoinstituto',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donoinstituto'),
        ),
    ]
