# Generated by Django 3.1 on 2020-10-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201030_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaServico',
        ),
    ]
