# Generated by Django 3.1 on 2020-10-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201030_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaproduto',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaproduto'),
        ),
    ]
