# Generated by Django 3.1 on 2020-10-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201031_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.CharField(max_length=100),
        ),
    ]
