# Generated by Django 3.1 on 2020-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201031_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
