# Generated by Django 3.1 on 2020-11-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201101_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donoinstituto'),
        ),
        migrations.AddField(
            model_name='servico',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donoinstituto'),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='instituto',
        ),
        migrations.AddField(
            model_name='produto',
            name='instituto',
            field=models.ManyToManyField(to='app.Instituto'),
        ),
        migrations.RemoveField(
            model_name='servico',
            name='instituto',
        ),
        migrations.AddField(
            model_name='servico',
            name='instituto',
            field=models.ManyToManyField(to='app.Instituto'),
        ),
    ]
