# Generated by Django 3.1 on 2020-11-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201103_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrostaff',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donoinstituto'),
        ),
    ]
