# Generated by Django 3.1 on 2020-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201104_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='static/images/institutos'),
        ),
    ]
