# Generated by Django 3.1 on 2020-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201105_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='foto',
            field=models.FileField(upload_to='static/images/institutos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(upload_to='static/images/produtos'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.FileField(upload_to='static/images/servicos'),
        ),
    ]
